"""
Day 20 lab: the CDN and cache invalidation, built for real on localhost.

This is the full working solution. The starter file is http_cache.py.
Run it:      python3 solution.py

Everything here is real. A real HTTP origin server in its own thread, real
Cache-Control and ETag headers, real conditional requests (If-None-Match), and
the origin really answers 304 Not Modified when nothing has changed. The edge
cache is an in-process object the "client" talks to, exactly the way your
browser talks to a CDN that then talks to your origin.

Standard library only. Runs in well under 40 seconds and makes no files on disk
(the cache lives in memory). The origin sleeps on purpose to stand in for real
work and the network round trip to a distant origin.

Three things we measure:
  Part 1  no cache. Every request reaches the origin. Count origin hits, time it.
  Part 2  a TTL cache at the edge. Serve the stored copy until max-age expires,
          then REVALIDATE with a conditional request so the origin can answer a
          cheap 304. Watch origin hits collapse and count the 304s.
  Part 3  stale-while-revalidate. When the copy is just past fresh, serve the
          STALE copy instantly and refresh in the background, so no user ever
          waits for the origin. Compare user latency against blocking
          revalidation, where the unlucky request eats the full origin trip.
"""

import hashlib
import http.client
import statistics
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

PREDICTIONS = {
    # P1: the workload is 120 requests (3 resources, 4 rounds, 10 reads each).
    #     With NO cache, how many of those reach the origin?
    "origin_hits_no_cache": 120,

    # P2: same 120 requests, now behind a TTL edge cache (max-age 0.3 s, and the
    #     rounds are spaced so the copy goes stale once between each). How many
    #     requests reach the origin now?
    "origin_hits_ttl_cache": 12,

    # P3: during that TTL run, how many of the origin trips come back as a cheap
    #     304 Not Modified (the revalidations where nothing had changed)?
    "revalidation_304s": 9,

    # P4: the unlucky request that triggers a BLOCKING revalidation waits for the
    #     origin while everyone else is served from the edge in ~1 ms. About how
    #     many ms does that one request wait? (stale-while-revalidate's worst
    #     request never waits for the origin, so it stays near 1 ms.)
    "blocking_spike_ms": 40,
}

# ---------------------------------------------------------------------------
# Config. Small, round numbers so the lab stays quick and the maths is clear.
# ---------------------------------------------------------------------------

RESOURCES = ["/img/logo.png", "/css/app.css", "/api/config.json"]
ROUNDS = 4                 # bursts of traffic, spaced so the cache goes stale
READS_PER_ROUND = 10       # reads per resource within a burst

ORIGIN_FULL_MS = 60        # a full 200: regenerate the body + the origin trip
ORIGIN_304_MS = 30         # a 304: no body, no regen, but you still pay the trip

MAX_AGE = 0.30             # seconds the edge treats a stored copy as fresh
SWR_WINDOW = 0.30          # extra seconds we are willing to serve it stale
EXPIRE_GAP = MAX_AGE + 0.05  # between-round sleep, just past fresh

HOT_KEY = "/feed/home"     # the single hot resource for part 3
P3_REQUESTS = 40           # sequential reads of the hot key
P3_GAP = 0.03              # seconds between those reads
SLOW_MS = 10               # a response slower than this "stalled" on the origin


def _silence(*a, **k):
    pass


def etag_for(path):
    """A content tag for a resource. It never changes in this lab, so every
    revalidation finds the content identical and the origin can say 304."""
    digest = hashlib.md5(path.encode()).hexdigest()[:8]
    return f'"{digest}-v1"'


def body_for(path):
    return (f"payload for {path}, generated by the origin\n" * 8).encode()


# ---------------------------------------------------------------------------
# The origin: a real HTTP server that does slow work and sets caching headers
# ---------------------------------------------------------------------------

class Origin:
    def __init__(self):
        self.lock = threading.Lock()
        self.hits = 0           # every request that reached the origin
        self.full_200 = 0       # full responses (did the slow work)
        self.not_modified = 0   # cheap 304 responses
        origin = self

        class Handler(BaseHTTPRequestHandler):
            log_message = _silence
            protocol_version = "HTTP/1.0"

            def do_GET(self):
                path = self.path
                etag = etag_for(path)
                inm = self.headers.get("If-None-Match")
                with origin.lock:
                    origin.hits += 1

                # Conditional request and the content is unchanged: 304, cheap.
                if inm is not None and inm == etag:
                    time.sleep(ORIGIN_304_MS / 1000)
                    with origin.lock:
                        origin.not_modified += 1
                    self.send_response(304)
                    self.send_header("ETag", etag)
                    self.send_header("Cache-Control", f"max-age={int(MAX_AGE * 1000)}")
                    self.end_headers()
                    return

                # Otherwise do the full work and return the body.
                time.sleep(ORIGIN_FULL_MS / 1000)
                body = body_for(path)
                with origin.lock:
                    origin.full_200 += 1
                self.send_response(200)
                self.send_header("ETag", etag)
                self.send_header("Cache-Control", f"max-age={int(MAX_AGE * 1000)}")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)

        self.srv = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self.srv.daemon_threads = True
        self.port = self.srv.server_address[1]
        threading.Thread(target=self.srv.serve_forever, daemon=True).start()

    def counters(self):
        with self.lock:
            return self.hits, self.full_200, self.not_modified

    def shutdown(self):
        try:
            self.srv.shutdown()
            self.srv.server_close()
        except Exception:
            pass


# ---------------------------------------------------------------------------
# The four lines that are the heart of the lab (the TODOs in the starter)
# ---------------------------------------------------------------------------

def is_fresh(stored_at, now, max_age):
    """True while a stored copy is still within its max-age (fresh)."""
    return (now - stored_at) < max_age


def conditional_headers(etag):
    """The conditional request. If-None-Match asks the origin 'only send a body
    if this tag no longer matches', which lets it reply 304 when nothing
    changed."""
    return {"If-None-Match": etag}


def slid_freshness(now):
    """After a 304, the stored body is still good, so we keep it and reset its
    clock: it counts as fresh again from now."""
    return now


def can_serve_stale(age, max_age, swr_window):
    """Stale-while-revalidate: once a copy is past max-age but still inside the
    stale window, we are allowed to hand it over immediately and refresh behind
    the scenes."""
    return max_age <= age < (max_age + swr_window)


# ---------------------------------------------------------------------------
# Talking to the origin over real HTTP
# ---------------------------------------------------------------------------

def http_get(port, path, inm=None):
    """One real HTTP GET. inm, if given, becomes an If-None-Match header.
    Returns (status, body, etag)."""
    headers = conditional_headers(inm) if inm is not None else {}
    conn = http.client.HTTPConnection("127.0.0.1", port, timeout=5.0)
    conn.request("GET", path, headers=headers)
    resp = conn.getresponse()
    body = resp.read()
    status = resp.status
    etag = resp.getheader("ETag")
    conn.close()
    return status, body, etag


# ---------------------------------------------------------------------------
# The edge cache: what the client talks to, the CDN in miniature
# ---------------------------------------------------------------------------

class EdgeCache:
    def __init__(self, origin_port, policy):
        self.port = origin_port
        self.policy = policy          # "blocking" or "swr"
        self.store = {}               # path -> {body, etag, stored_at, refreshing}
        self.lock = threading.Lock()
        self.origin_fetches = 0
        self.threads = []

    def _fetch(self, path, inm=None):
        with self.lock:
            self.origin_fetches += 1
        return http_get(self.port, path, inm=inm)

    def _store_entry(self, path, body, etag, when):
        self.store[path] = {"body": body, "etag": etag,
                            "stored_at": when, "refreshing": False}

    def get(self, path):
        """Serve one request. Returns (body, user_latency_ms, kind)."""
        start = time.perf_counter()
        with self.lock:
            entry = self.store.get(path)

        # Cold miss: nothing stored yet, fetch the full body.
        if entry is None:
            status, body, etag = self._fetch(path)
            with self.lock:
                self._store_entry(path, body, etag, time.perf_counter())
            return body, (time.perf_counter() - start) * 1000, "miss"

        now = time.perf_counter()
        if is_fresh(entry["stored_at"], now, MAX_AGE):
            return entry["body"], (time.perf_counter() - start) * 1000, "hit"

        # Past fresh. Under stale-while-revalidate we hand over the old copy at
        # once and refresh in the background, so the user never waits.
        if self.policy == "swr" and can_serve_stale(now - entry["stored_at"], MAX_AGE, SWR_WINDOW):
            self._background_refresh(path, entry)
            return entry["body"], (time.perf_counter() - start) * 1000, "stale"

        # Blocking revalidation: this request pays the origin trip itself.
        status, body, etag = self._fetch(path, inm=entry["etag"])
        if status == 304:
            with self.lock:
                entry["stored_at"] = slid_freshness(time.perf_counter())
            served, kind = entry["body"], "revalidate_304"
        else:
            with self.lock:
                entry["body"], entry["etag"] = body, etag
                entry["stored_at"] = time.perf_counter()
            served, kind = body, "revalidate_200"
        return served, (time.perf_counter() - start) * 1000, kind

    def _background_refresh(self, path, entry):
        """Kick off at most one background revalidation per entry."""
        with self.lock:
            if entry["refreshing"]:
                return
            entry["refreshing"] = True

        def worker():
            try:
                status, body, etag = self._fetch(path, inm=entry["etag"])
                with self.lock:
                    if status != 304:
                        entry["body"], entry["etag"] = body, etag
                    entry["stored_at"] = time.perf_counter()
                    entry["refreshing"] = False
            except Exception:
                with self.lock:
                    entry["refreshing"] = False

        t = threading.Thread(target=worker, daemon=True)
        t.start()
        with self.lock:
            self.threads.append(t)

    def drain(self):
        for t in list(self.threads):
            t.join(timeout=3)


# ---------------------------------------------------------------------------
# The workload for parts 1 and 2: the same 120 requests, spaced into rounds
# ---------------------------------------------------------------------------

def run_rounds(serve):
    """Fire ROUNDS bursts. In each burst, read every resource READS_PER_ROUND
    times. Sleep just past fresh between bursts, so a TTL cache goes stale once
    per gap. `serve(path)` returns a latency in ms. Returns all latencies."""
    lats = []
    for r in range(ROUNDS):
        if r > 0:
            time.sleep(EXPIRE_GAP)
        for path in RESOURCES:
            for _ in range(READS_PER_ROUND):
                lats.append(serve(path))
    return lats


def part1():
    print("=" * 78)
    print("Part 1: no cache. Every request walks all the way to the origin.")
    print("=" * 78)
    origin = Origin()

    def serve(path):
        t0 = time.perf_counter()
        http_get(origin.port, path)
        return (time.perf_counter() - t0) * 1000

    lats = run_rounds(serve)
    hits, full, nm = origin.counters()
    origin.shutdown()

    total = ROUNDS * len(RESOURCES) * READS_PER_ROUND
    print(f"  requests sent by the client:      {total}")
    print(f"  requests that reached the origin: {hits}  (every single one)")
    print(f"  average user latency:             {statistics.mean(lats):6.1f} ms")
    print("  No copy is kept anywhere, so the client pays the full origin cost")
    print("  on every read, even for the same three resources over and over.")
    return hits, statistics.mean(lats)


def part2():
    print("\n" + "=" * 78)
    print("Part 2: a TTL edge cache. Serve the stored copy until it goes stale,")
    print("        then revalidate with a conditional request (If-None-Match).")
    print("=" * 78)
    origin = Origin()
    cache = EdgeCache(origin.port, policy="blocking")

    lats = run_rounds(lambda p: cache.get(p)[1])
    cache.drain()
    hits, full, nm = origin.counters()
    origin.shutdown()

    total = ROUNDS * len(RESOURCES) * READS_PER_ROUND
    print(f"  requests sent by the client:      {total}")
    print(f"  requests that reached the origin: {hits}")
    print(f"    of those, full 200 responses:   {full}")
    print(f"    of those, cheap 304 responses:  {nm}")
    print(f"  average user latency:             {statistics.mean(lats):6.1f} ms")
    print("  The first read of each resource is a miss and fetches the body. After")
    print("  that, reads inside a fresh window are served from the edge for free.")
    print("  When a burst finds the copy stale, the edge asks the origin 'changed?'")
    print("  and the origin replies 304, no body, so the refresh is cheap.")
    return hits, nm, statistics.mean(lats)


# ---------------------------------------------------------------------------
# Part 3: stale-while-revalidate vs blocking revalidation, one hot key
# ---------------------------------------------------------------------------

def hammer_hot_key(policy):
    """Prewarm the hot key, then read it P3_REQUESTS times with a small gap, so
    the copy keeps going stale. Return (latencies_ms, origin_fetches)."""
    origin = Origin()
    cache = EdgeCache(origin.port, policy=policy)
    cache.get(HOT_KEY)  # prewarm: one cold miss

    lats = []
    for _ in range(P3_REQUESTS):
        _, lat, _ = cache.get(HOT_KEY)
        lats.append(lat)
        time.sleep(P3_GAP)

    cache.drain()
    fetches = cache.origin_fetches
    origin.shutdown()
    return lats, fetches


def summarize(lats):
    hot = sorted(lats)[-1]
    slow = sum(1 for x in lats if x > SLOW_MS)
    return statistics.median(lats), hot, slow


def part3():
    print("\n" + "=" * 78)
    print("Part 3: one hot key, read over and over as it keeps going stale.")
    print("        Blocking revalidation vs stale-while-revalidate.")
    print("=" * 78)
    block_lats, block_fetch = hammer_hot_key("blocking")
    swr_lats, swr_fetch = hammer_hot_key("swr")

    b_med, b_max, b_slow = summarize(block_lats)
    s_med, s_max, s_slow = summarize(swr_lats)
    spike_ratio = b_max / s_max if s_max else float("inf")

    print(f"  {'policy':<26} {'median ms':>10} {'worst ms':>10} {'slow reqs':>10} {'origin trips':>13}")
    print(f"  {'blocking revalidation':<26} {b_med:>10.1f} {b_max:>10.1f} {b_slow:>10} {block_fetch:>13}")
    print(f"  {'stale-while-revalidate':<26} {s_med:>10.1f} {s_max:>10.1f} {s_slow:>10} {swr_fetch:>13}")
    print(f"  worst-case spike, blocking / swr: {spike_ratio:.1f}x")
    print("  Both policies hit the origin about the same number of times, so SWR is")
    print("  not cheating the origin. The difference is WHO waits. Under blocking,")
    print("  the one request that finds the copy stale is stuck paying the origin")
    print("  trip while everyone else is served from the edge. Under SWR, that")
    print("  request gets the slightly old copy instantly and the refresh happens")
    print("  behind it, so the worst user latency stays flat.")
    return b_max, s_max, spike_ratio


# ---------------------------------------------------------------------------

def verdict(name, predicted, actual, unit=""):
    if predicted is None:
        print(f"  {name:<32} actual = {actual:>8,.1f} {unit}  (no prediction)")
        return
    ratio = actual / predicted if predicted else float("inf")
    if 0.5 <= ratio <= 2.0:
        note = "     close enough"
    elif ratio > 1:
        note = f"{ratio:>6.1f}x  too LOW"
    else:
        note = f"{1 / ratio:>6.1f}x  too HIGH"
    print(f"  {name:<32} you = {predicted:>7,.1f}   actual = {actual:>8,.1f} {unit}  {note}")


def self_test():
    """Check the four TODO lines before any load runs, so a blank TODO stops the
    lab cleanly instead of hanging. Returns a list of complaints, empty if all
    four are wired up."""
    missing = []
    if is_fresh(0.0, 0.1, 1.0) is None:
        missing.append("TODO 1: is_fresh returns None")
    if conditional_headers('"abc"') is None:
        missing.append("TODO 2: conditional_headers returns None")
    if slid_freshness(123.0) is None:
        missing.append("TODO 3: slid_freshness returns None")
    if can_serve_stale(0.4, 0.3, 0.3) is None:
        missing.append("TODO 4: can_serve_stale returns None")
    return missing


def main():
    if all(v is None for v in PREDICTIONS.values()):
        print("\n  !! No predictions yet. Open this file, fill in PREDICTIONS,")
        print("     then run again. The surprise is the lesson, so earn it.\n")
        sys.exit(1)

    gaps = self_test()
    if gaps:
        print("\n  !! Some TODOs are not filled in yet:")
        for g in gaps:
            print(f"       - {g}")
        print("     Fill them in and run again. See solution.py if you get stuck.\n")
        sys.exit(1)

    hits_nocache, lat_nocache = part1()
    hits_ttl, nm_ttl, lat_ttl = part2()
    block_max, swr_max, spike_ratio = part3()

    print("\n" + "=" * 78)
    print("Scoreboard")
    print("=" * 78)
    verdict("P1 origin hits, no cache", PREDICTIONS["origin_hits_no_cache"], hits_nocache, "")
    verdict("P2 origin hits, TTL cache", PREDICTIONS["origin_hits_ttl_cache"], hits_ttl, "")
    verdict("P3 cheap 304 revalidations", PREDICTIONS["revalidation_304s"], nm_ttl, "")
    verdict("P4 blocking spike (ms)", PREDICTIONS["blocking_spike_ms"], block_max, "ms")

    print("\n" + "=" * 78)
    print("The number to carry")
    print("=" * 78)
    drop = hits_nocache / hits_ttl if hits_ttl else float("inf")
    print(f"  Same 120 requests for the same 3 resources. With no cache, {hits_nocache} of")
    print(f"  them hit the origin. With a TTL edge cache, {hits_ttl}: a {drop:.0f}x cut, and")
    print(f"  {nm_ttl} of those were cheap 304s because nothing had changed.")
    print(f"  Average user latency fell from {lat_nocache:.0f} ms to {lat_ttl:.0f} ms.")
    print(f"  And stale-while-revalidate kept the worst request at {swr_max:.0f} ms while")
    print(f"  blocking revalidation spiked to {block_max:.0f} ms: {spike_ratio:.0f}x worse for the")
    print(f"  one unlucky user who happened to arrive the moment the copy expired.")
    print("\nNow write labs/day-20-cdn/RESULTS.md.\n")


if __name__ == "__main__":
    main()
